#! /usr/bin/env node
"use strict";

// http://stackoverflow.com/a/8808162/449477
var vm = require("vm")
var fs = require("fs")
function load(path, context) {
  var data = fs.readFileSync(path, "utf8")
  vm.runInThisContext(data, path)
}

load("./NULAN.js")
load("./NULAN.parse.js")

load("./lib/NUIT.parse.js")


var util = require("util")

function foo(a) {
  a.forEach(function (x) {
    try {
      NULAN.parse(x + (Math.random() < 0.5 ? "\n" : ""), function (x) {
        console.log(util.inspect(NULAN.toJSON(x), false, null, true))
      })
    } catch (e) {
      console.error("" + e)
    }
    console.log()
  })
}

fs.readFile("test/parse", "utf8", function (err, s) {
  foo(NUIT.parse(s))
})

// ( foo 10 ( ( bar.qux 20 30 ) . corge 40 50 ) )
